name: Compilar Mod Menu

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Android NDK
      uses: android-actions/setup-android@v2
    
    - name: Compilar Biblioteca (.so)
      run: |
        cd app/src/main
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./jni/Android.mk APP_APPLICATION_MK=./jni/Application.mk
        
    - name: Upload do Arquivo Pronto
      uses: actions/upload-artifact@v3
      with:
        name: Lib-Compilada
        path: app/src/main/libs/armeabi-v7a/
